#!/bin/bash
set -e

CURRENT_VERSION_CHROMIUM=`docker container run --rm --entrypoint "" zenika/alpine-chrome:with-node chromium-browser --version`
echo ${CURRENT_VERSION_CHROMIUM:9:2}
CURRENT_NODE_VERSION=`docker container run --rm --entrypoint "" zenika/alpine-chrome:with-node node -v`
echo ${CURRENT_NODE_VERSION:1:2}

for tag in ${CURRENT_VERSION_CHROMIUM:9:2}; do
    echo $tag        
    tagStart=$(expr index "$IMAGE_NAME" :)
    repoName=${IMAGE_NAME:0:tagStart-1}
    docker tag $IMAGE_NAME ${repoName}:${tag}-with-node
    docker push ${repoName}:${tag}-with-node
    docker tag $IMAGE_NAME ${repoName}:${tag}-with-node-${CURRENT_NODE_VERSION:1:2}
    docker push ${repoName}:${tag}-with-node-${CURRENT_NODE_VERSION:1:2}
done
