#!/bin/bash
set -e

CURRENT_VERSION_CHROMIUM=`docker container run --rm --entrypoint "" zenika/alpine-chrome:with-chromedriver chromium-browser --version`
echo ${CURRENT_VERSION_CHROMIUM:9:2}
CURRENT_CHROMEDRIVER_VERSION=`docker container run --rm --entrypoint "" zenika/alpine-chrome:with-chromedriver chromedriver -v`
echo ${CURRENT_CHROMEDRIVER_VERSION:13:2}

for tag in ${CURRENT_VERSION_CHROMIUM:9:2}; do
    echo $tag        
    tagStart=$(expr index "$IMAGE_NAME" :)
    repoName=${IMAGE_NAME:0:tagStart-1}
    docker tag $IMAGE_NAME ${repoName}:${tag}-with-chromedriver 
    docker push ${repoName}:${tag}-with-chromedriver 
    docker tag $IMAGE_NAME ${repoName}:${tag}-with-chromedriver-${CURRENT_CHROMEDRIVER_VERSION:13:2}
    docker push ${repoName}:${tag}-with-chromedriver-${CURRENT_CHROMEDRIVER_VERSION:13:2}
done
