---

name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-base:
    uses: ./.github/workflows/build-one.yml
    with:
      folder: .
      tag: latest

  build-with-node:
    needs:
      - build-base
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-node
      tag: with-node

  build-with-deno:
    needs:
      - build-base
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-deno
      tag: with-deno

  build-with-chromedriver:
    needs:
      - build-base
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-chromedriver
      tag: with-chromedriver

  build-with-playwright:
    needs:
      - build-with-node
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-playwright
      tag: with-playwright

  build-with-puppeteer:
    needs:
      - build-with-node
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-puppeteer
      tag: with-puppeteer

  build-with-puppeteer-xvfb:
    needs:
      - build-with-puppeteer
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-puppeteer-xvfb
      tag: with-puppeteer-xvfb

  build-with-selenoid:
    needs:
      - build-with-chromedriver
    uses: ./.github/workflows/build-one.yml
    with:
      folder: with-selenoid
      tag: with-selenoid
